FROM centos:8.1.1911

ENV WILDFLY_VERSION=20.0.1.Final

RUN yum update -y
RUN yum install wget -y
RUN yum install java-11-openjdk -y

RUN wget -O /tmp/wildfly.tar.gz https://download.jboss.org/wildfly/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.tar.gz
RUN tar xf /tmp/wildfly.tar.gz -C /opt/
RUN mkdir /opt/jboss/ && mv /opt/wildfly-${WILDFLY_VERSION}/ /opt/jboss/wildfly

CMD /opt/jboss/wildfly/bin/standalone.sh